services:
  db:
    image: postgres:13
    ports:
      - "5431:5431"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    command: postgres -c port=5431
    healthcheck:
      test: pg_isready -h ${DB_HOST} -p 5431 -d ${DB_NAME} -U ${DB_USER}
      interval: 1s
      timeout: 3s
      retries: 20

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_DRIV=${DB_DRIV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=5431
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      db:
        condition: service_healthy
