services:
  db:
    volumes:
      - "~/Documents:/app/Documents/"
    image: postgres:13
    environment:
      - PGUSER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 1s
      timeout: 3s
      retries: 60
    attach: false

  redis:
    image: redis:6
    attach: false

  celery:
    build: .
    volumes:
      - "~/Documents:/app/Documents/"
    command: celery -A app.services.celery worker --loglevel=info
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    attach: false

  flower:
    build: .
    volumes:
      - "~/Documents:/app/Documents/"
    command: celery -A app.services.celery flower
    ports:
      - "5555:5555"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - celery
    attach: false

  app:
    build: .
    volumes:
      - "~/Documents:/app/Documents/"
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      db:
        condition: service_healthy
    attach: false

  test:
    build: .
    volumes:
      - "~/Documents:/app/Documents/"
    command: python -m pytest -v . -W ignore::DeprecationWarning
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - app
