[tool.pytest.ini_options]
pythonpath = [
    ".", "src",
]
asyncio_mode = "auto"
#filterwarnings = ["ignore::DeprecationWarning", "ignore::PendingDeprecationWarning", "ignore::ImportWarning", "ignore::ResourceWarning"]





